<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRaSLqIc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRaSLqIc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRaSLqIc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRaSLqIc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRaSLqIc\App_KernelDevDebugContainer([
    'container.build_hash' => 'RaSLqIc',
    'container.build_id' => '7250a0e2',
    'container.build_time' => 1714003617,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRaSLqIc');
